[Scans]
; Different address for different purpose but we reuse the same name.
QuickQuestCheckAddr = 0F 94 83 ?? ?? ?? ?? 48 8B 35
QuickQuestCheckCondAddr = 3B 05 ?? ?? ?? ?? 0F 94 87
GiveQuickQuestRewardCheckAddr = 0F 84 ?? ?? ?? ?? 8B 06 C1 E8